export default {
  ADD_SCHOOL: {
    ALL_KEY: [
      'First name',
      'Last name',
      'Phone number',
      'Email ID',
      'School name',
      'School type',
      'No. of student accounts',
      'No. of teacher accounts',
      'No. of admin accounts',
      'Grades Supported',
      'Address Line 1',
      'Address Line 2',
      'District',
      'State',
      'Country',
      'Postal Code'
    ],
    ADMIN_DETAILS: {
      TITLE: 'Admin details',
      FIRST_NAME: 'First name',
      LAST_NAME: 'Last name',
      PHONE_NUMBER: 'Phone number',
      EMAIL: 'Email ID',
      BODY: 'This user would be POC for this school'
    },
    SCHOOL_DETAILS: {
      TITLE: 'School details',
      SCHOOL_NAME: 'School name',
      SCHOOL_TYPE: 'School type',
      SCHOOL_TYPE_DATA: [
        'Public',
        'Public (Virtual)',
        'Private',
        'Charter',
        'Magnet',
        'MicroSchool'
      ],
      NO_OF_STUDENT_ACCOUNTS: 'No. of student accounts',
      NO_OF_TEACHER_ACCOUNTS: 'No. of teacher accounts',
      NO_OF_ADMIN_ACCOUNTS: 'No. of admin accounts',
      GRADES_SUPPORTED: 'Grades Supported',
      GRADES_SUPPORTED_DATA: [
        'K-2 (Elementary)',
        '3-5 (Upper Elementary)',
        '6-8 (Middle)',
        '9-12 (High)'
      ],
      BODY: ''
    },
    LOCATION_DETAILS: {
      TITLE: 'Location details',
      ADDRESS_LINE_1: 'Address Line 1',
      ADDRESS_LINE_2: 'Address Line 2',
      DISTRICT: 'District',
      STATE: 'State',
      COUNTRY: 'Country',
      POSTAL_CODE: 'Postal Code',
      BODY: 'This information is necessary to plan the game sessions'
    }
  },
  ADD_ACCOUNT: {
    TOMOADMIN_OPTION: [
      ['Add Disrict Admin', '/accounts/adddistrictadmin'],
      ['Add School', '/accounts/addschool'],
      ['Add Teacher', '/accounts/addteacher?activeTab=addTeacher'],
      ['Add Student', '/accounts/addstudent'],
      ['Add Experts', '/moderators/add']
    ]
  },
  ACCOUNTS: ['District Admin', 'School', 'Teacher', 'Student', 'Experts'],
  STATUS: ['Active', 'Inactive'],
  TEACHER_BULK_DOWNLOAD:
    'https://bulk-download-template.s3.us-east-1.amazonaws.com/Teacher_upload_template.csv',
  STUDENT_BULK_DOWNLOAD:
    'https://bulk-student-upload.s3.us-east-1.amazonaws.com/Student_upload_template.csv',
  TIMEZONE: ['AKST', 'PST', 'MST', 'CST', 'EST', 'AST', 'IST'],
  DAY: ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
  TIME: [
    '12:00 AM',
    '01:00 AM',
    '02:00 AM',
    '03:00 AM',
    '04:00 AM',
    '05:00 AM',
    '06:00 AM',
    '07:00 AM',
    '08:00 AM',
    '09:00 AM',
    '10:00 AM',
    '11:00 AM',
    '12:00 PM',
    '01:00 PM',
    '02:00 PM',
    '03:00 PM',
    '04:00 PM',
    '05:00 PM',
    '06:00 PM',
    '07:00 PM',
    '08:00 PM',
    '09:00 PM',
    '10:00 PM',
    '11:00 PM'
  ],
  GRADE: [
    'Pre-Kindergarten (Pre-K)',
    'Kindergarten (K)',
    '1st Grade',
    '2nd Grade',
    '3rd Grade',
    '4th Grade',
    '5th Grade',
    '6th Grade',
    '7th Grade',
    '8th Grade',
    '9th Grade',
    '10th Grade',
    '11th Grade',
    '12th Grade'
  ],
  COUNTRY: ['The US', 'India'],
  STATES: {
    'The US': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming'
    ],
    India: [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal'
    ]
  }
};
